spring.application.name=pdfTagging
server.port=8000

#aws properties
aws.region=us-east-1
pdf.local.base-dir=C:\\projects\\pdf\\data\\

#chatgpt properties
chatgpt.open-api.uri = https://api.openai.com/v1/chat/completions
chatgpt.open-api.model = gpt-4-turbo
chatgpt.open-api.role = user

logging.level.root=INFO
logging.level.com.netralab.pdfTagging=INFO
logging.config=classpath:logback-spring.xml

#Run jar using below command
#java -DAWS_ACCESS_KEY="value" -DAWS_SECRET_KEY="value" -DCHATGPT_KEY="value" -jar .\pdfTagging-0.0.1-SNAPSHOT.jar